// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: invoice.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addInvoice = `-- name: AddInvoice :one

INSERT INTO Invoice (date, payment_type_id) VALUES ($1, $2) RETURNING id
`

type AddInvoiceParams struct {
	Date          int64 `json:"date"`
	PaymentTypeID int32 `json:"payment_type_id"`
}

// queries/invoice.sql
func (q *Queries) AddInvoice(ctx context.Context, arg AddInvoiceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addInvoice, arg.Date, arg.PaymentTypeID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE Invoice SET total = $1 WHERE id = $2 RETURNING id
`

type UpdateInvoiceParams struct {
	Total sql.NullInt32 `json:"total"`
	ID    int32         `json:"id"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateInvoice, arg.Total, arg.ID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
