// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Invoice struct {
	ID            int32         `json:"id"`
	Total         sql.NullInt32 `json:"total"`
	Date          int64         `json:"date"`
	PaymentTypeID int32         `json:"payment_type_id"`
}

type PaymentType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Product struct {
	ID          int32  `json:"id"`
	Utc         string `json:"utc"`
	Name        string `json:"name"`
	Price       int32  `json:"price"`
	GrossMargin int32  `json:"gross_margin"`
	Iva         int32  `json:"iva"`
}

type Sale struct {
	ID        int32 `json:"id"`
	ProductID int32 `json:"product_id"`
	InvoiceID int32 `json:"invoice_id"`
	Quantity  int32 `json:"quantity"`
	Price     int32 `json:"price"`
	Iva       int32 `json:"iva"`
	Subtotal  int32 `json:"subtotal"`
}
