// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: product.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const addProduct = `-- name: AddProduct :one
INSERT INTO Product (name, price, iva, gross_margin) VALUES ($1, $2, $3, $4) RETURNING id
`

type AddProductParams struct {
	Name        string `json:"name"`
	Price       int32  `json:"price"`
	Iva         int32  `json:"iva"`
	GrossMargin int32  `json:"gross_margin"`
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addProduct,
		arg.Name,
		arg.Price,
		arg.Iva,
		arg.GrossMargin,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM Product WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many

SELECT id, name, price, gross_margin, iva FROM Product
`

// queries/product.sql
func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.GrossMargin,
			&i.Iva,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredProducts = `-- name: GetFilteredProducts :many
SELECT id, name, price, gross_margin, iva
    FROM Product
    WHERE to_char(id, '9999999') LIKE '%' || $1 || '%'
        OR name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetFilteredProducts(ctx context.Context, dollar_1 sql.NullString) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getFilteredProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.GrossMargin,
			&i.Iva,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price, gross_margin, iva FROM Product WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.GrossMargin,
		&i.Iva,
	)
	return i, err
}

const getProductsByID = `-- name: GetProductsByID :many
SELECT id, name, price, gross_margin, iva FROM Product WHERE id = ANY($1::int[])
`

func (q *Queries) GetProductsByID(ctx context.Context, dollar_1 []int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getProductsByID, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.GrossMargin,
			&i.Iva,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE Product SET name = $1, price = $2, iva = $3, gross_margin = $4 WHERE id = $5 RETURNING id, name, price, gross_margin, iva
`

type UpdateProductParams struct {
	Name        string `json:"name"`
	Price       int32  `json:"price"`
	Iva         int32  `json:"iva"`
	GrossMargin int32  `json:"gross_margin"`
	ID          int32  `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Price,
		arg.Iva,
		arg.GrossMargin,
		arg.ID,
	)
	return err
}
