// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sales.sql

package sqlc

import (
	"context"
)

const addSales = `-- name: AddSales :one

INSERT INTO Sales (product_id, invoice_id, quantity, price, iva, subtotal) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type AddSalesParams struct {
	ProductID int32 `json:"product_id"`
	InvoiceID int32 `json:"invoice_id"`
	Quantity  int32 `json:"quantity"`
	Price     int32 `json:"price"`
	Iva       int32 `json:"iva"`
	Subtotal  int32 `json:"subtotal"`
}

// queries/sales.sql
func (q *Queries) AddSales(ctx context.Context, arg AddSalesParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addSales,
		arg.ProductID,
		arg.InvoiceID,
		arg.Quantity,
		arg.Price,
		arg.Iva,
		arg.Subtotal,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
